{% set version = "2.5.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-haven
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/haven_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/haven/haven_{{ version }}.tar.gz
  sha256: 9482cd9c3760e1838acf687235317fed97fa6bf79219d3216f0ea447d4b1c9a5
  #patches:
  #  - r-haven-libiconv.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cli                        # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - r-forcats                    # [build_platform != target_platform]
    - r-hms                        # [build_platform != target_platform]
    - r-lifecycle                  # [build_platform != target_platform]
    - r-readr                      # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-tibble                     # [build_platform != target_platform]
    - r-tidyselect                 # [build_platform != target_platform]
    - r-vctrs                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=3.0.0
    - r-cpp11
    - r-forcats >=0.2.0
    - r-hms
    - r-lifecycle
    - r-readr >=0.1.0
    - r-rlang >=0.4.0
    - r-tibble
    - r-tidyselect
    - r-vctrs >=0.3.0
    - zlib
  run:
    - r-base
    - r-cli >=3.0.0
    - r-cpp11
    - r-forcats >=0.2.0
    - r-hms
    - r-lifecycle
    - r-readr >=0.1.0
    - r-rlang >=0.4.0
    - r-tibble
    - r-tidyselect
    - r-vctrs >=0.3.0

test:
  commands:
    - $R -e "library('haven')"           # [not win]
    - "\"%R%\" -e \"library('haven')\""  # [win]

about:
  home: http://haven.tidyverse.org, https://github.com/WizardMac/ReadStat
  dev_url: https://github.com/tidyverse/haven
  license: MIT
  summary: Import foreign statistical formats into R via the embedded 'ReadStat' C library, <https://github.com/WizardMac/ReadStat>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
