appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UtfeOQu6m+RKkDlPdxTUdPXPWZ9TipwGfxw/h4OJWPskYy04/utCH0h5QhNQ2pPrSa8TD4yjTa0QHuju6zGKNIjx3bRaPLCawoopKzopMnHz5PxTp1W7YE9NXa7BsHkNAV+l9/ZwcsS75pBbiOSiq+eBq5nsJ/BAOCyebk+Cx2mDZcFGmI3Ege3tFLTj747iu522MzmBTBJ73Ue9Ajdx/7cVeyRgNbInZff27FPDBqAtUq5a6O1gsS2rzEEtYuj5y7Zvu+1du64BoKVEw8piHtxw1uy9B3BGCY0nN9pvwtPgUBe0vBWee/UBys2Dq4UuyQf8w9J+GXU6Tc6F0SrEMKW1MkWOKG8/1xva0g6qRR1zEEH8QRYsExgQjxqR1b5ezCyBVpdLrbSd93RgBJBggDqHjeR0+iNpJhz/TQPdFCclO9Hyp8MWCRpRXcHWfa5O6PrWQksFdM1aSanxNs9LFGguM+ge0PlLHKmcVSYS3pDZPxhlMXgX6cyM7+bDx9NxA2g5uHtBXuKureq+IjbAGGby+X8Fx185FbrCv9FF7gECP/KRo2FZ2X2pcqEBYWBMtSzDVVf3KzqzJWiRqANpSnCMS2VvzLgH4T3kXPjfUX/VUSEloDV3Zjx0ZKo4KcnwQ2Y4a9vXUbMulT+R2Zsp7sJtmX6MmUXX2Ywvv40KPjc=}
